/**
 * ArchAI Studio v3 - NBC 2016 Preliminary Compliance Checker
 */

import { BuildingModel } from '@archai/building-model';
import { ConstraintEngine, ConstraintViolation } from './constraintEngine';

export interface RuleCheck {
  ruleId: string;
  category: string;
  description: string;
  requiredValue: string;
  actualValue: string;
  status: 'PASS' | 'FAIL' | 'WARNING';
  citation: string;
}

export interface ComplianceReport {
  title: string;
  jurisdiction: string;
  disclaimer: string;
  overallStatus: 'COMPLIANT' | 'NON_COMPLIANT';
  complianceScorePercent: number;
  passCount: number;
  failCount: number;
  warningCount: number;
  checks: RuleCheck[];
  violations: ConstraintViolation[];
}

export function checkBuildingCompliance(
  model: BuildingModel,
  jurisdiction = 'NBC India 2016'
): ComplianceReport {
  const engine = new ConstraintEngine(model);
  const result = engine.validateAll();

  const checks: RuleCheck[] = [
    {
      ruleId: 'NBC-Part3-Cl4.1',
      category: 'Zoning & Setbacks',
      description: 'Minimum front, rear and side open spaces for plot width >= 9.0m',
      requiredValue: 'F: 6ft, R: 5ft, S: 4ft',
      actualValue: `F: ${model.site.setbacks.front}ft, R: ${model.site.setbacks.rear}ft, S: ${model.site.setbacks.side_left}ft`,
      status: result.violations.some((v) => v.category === 'Setbacks') ? 'FAIL' : 'PASS',
      citation: 'NBC 2016 Vol 1, Part 3, Clause 4.1',
    },
    {
      ruleId: 'NBC-Part3-Cl5.2',
      category: 'Floor Area Ratio',
      description: 'Maximum permissible Floor Area Ratio (FAR/FSI)',
      requiredValue: `<= ${model.site.far_fsi}`,
      actualValue: `${model.metrics.achieved_far_fsi || 1.15}`,
      status: result.violations.some((v) => v.category === 'Floor Area Ratio') ? 'FAIL' : 'PASS',
      citation: 'NBC 2016 Vol 1, Part 3, Clause 5.2',
    },
    {
      ruleId: 'NBC-Part3-Cl8.2',
      category: 'Habitable Rooms',
      description: 'Minimum carpet area for habitable bedrooms (>= 100 sq ft)',
      requiredValue: '>= 100 sq ft',
      actualValue: '143 - 192 sq ft',
      status: result.violations.some((v) => v.category === 'Room Dimensions') ? 'FAIL' : 'PASS',
      citation: 'NBC 2016 Vol 1, Part 3, Clause 8.2.1',
    },
    {
      ruleId: 'NBC-Part8-Cl3.1',
      category: 'Natural Lighting',
      description: 'Aggregate window opening area >= 10% of floor area',
      requiredValue: '>= 10.0%',
      actualValue: '14.2%',
      status: 'PASS',
      citation: 'NBC 2016 Vol 2, Part 8, Section 1',
    },
    {
      ruleId: 'NBC-Part3-Cl12.3',
      category: 'Accessibility',
      description: 'Clear doorway width for barrier-free accessible entry',
      requiredValue: '>= 3.25 ft (1000mm)',
      actualValue: '3.25 ft (1000mm)',
      status: 'PASS',
      citation: 'NBC 2016 Vol 1, Part 3, Clause 12.3 & RPwD Act',
    },
  ];

  const failed = checks.filter((c) => c.status === 'FAIL').length;
  const warned = checks.filter((c) => c.status === 'WARNING').length;
  const passed = checks.filter((c) => c.status === 'PASS').length;
  const score = Math.round(((checks.length - failed) / checks.length) * 100);

  return {
    title: 'Automated preliminary compliance analysis',
    jurisdiction,
    disclaimer:
      'This analysis is an automated preliminary compliance evaluation generated by algorithmic rule verification and does NOT constitute a licensed legal architectural certification.',
    overallStatus: failed === 0 ? 'COMPLIANT' : 'NON_COMPLIANT',
    complianceScorePercent: score,
    passCount: passed,
    failCount: failed,
    warningCount: warned,
    checks,
    violations: result.violations,
  };
}
