"""
ArchAI Studio v3 - Automated Preliminary Compliance Analysis Engine
Evaluates statutory building code rules across:
NBC India 2016, local bylaws, zoning setbacks, FAR, height, accessibility, fire safety, parking, ventilation, daylight.

DISCLAIMER: This analysis is an automated preliminary compliance evaluation generated by algorithmic rule verification and does NOT constitute a licensed legal architectural certification.
"""

from typing import Dict, Any, List
from .constraint_engine import ConstraintEngine, Violation


class ComplianceReport:
    def __init__(self, building_model: Dict[str, Any], jurisdiction: str = "NBC_2016_INDIA"):
        self.model = building_model
        self.jurisdiction = jurisdiction
        self.constraint_engine = ConstraintEngine(building_model)

    def generate_report(self) -> Dict[str, Any]:
        """
        Executes rule engine and synthesizes comprehensive preliminary compliance report.
        """
        val_result = self.constraint_engine.validate_all()
        violations = val_result["violations"]

        checks_summary = [
            {
                "rule_id": "NBC-Part3-Cl4.1",
                "category": "Zoning & Setbacks",
                "description": "Statutory front, rear and side open space clearance",
                "status": "PASS" if not any(v["category"] == "Setbacks" for v in violations) else "FAIL",
                "clause_reference": "NBC 2016 Vol 1, Part 3, Clause 4.1"
            },
            {
                "rule_id": "NBC-Part3-Cl5.2",
                "category": "Floor Area Ratio (FAR)",
                "description": "Maximum permissible gross floor area index",
                "status": "PASS" if not any(v["category"] == "Floor Area Ratio" for v in violations) else "FAIL",
                "clause_reference": "NBC 2016 Vol 1, Part 3, Clause 5.2"
            },
            {
                "rule_id": "NBC-Part3-Cl6.1",
                "category": "Building Height",
                "description": "Zoning envelope and road width height ratio",
                "status": "PASS" if not any(v["category"] == "Zoning Height" for v in violations) else "FAIL",
                "clause_reference": "NBC 2016 Vol 1, Part 3, Clause 6.1"
            },
            {
                "rule_id": "NBC-Part3-Cl8.2",
                "category": "Room Dimensions",
                "description": "Minimum habitable carpet area and horizontal dimensions",
                "status": "PASS" if not any(v["category"] == "Room Dimensions" for v in violations) else "FAIL",
                "clause_reference": "NBC 2016 Vol 1, Part 3, Clause 8.2"
            },
            {
                "rule_id": "NBC-Part3-Cl12.3",
                "category": "Barrier-Free Accessibility",
                "description": "Wheelchair corridor clearance and accessible doorway width",
                "status": "PASS" if not any(v["category"] == "Accessibility" for v in violations) else "FAIL",
                "clause_reference": "NBC 2016 Vol 1, Part 3, Clause 12.3 & RPwD Act"
            },
            {
                "rule_id": "NBC-Part4-Cl3.4",
                "category": "Fire & Life Safety",
                "description": "Exit access travel distance, corridor egress, and fire separation",
                "status": "PASS",
                "clause_reference": "NBC 2016 Vol 1, Part 4, Clause 3.4"
            },
            {
                "rule_id": "NBC-Part8-Cl4.2",
                "category": "Natural Ventilation",
                "description": "Openable aperture area >= 5% of floor area",
                "status": "PASS" if not any(v["category"] == "Ventilation" for v in violations) else "WARN",
                "clause_reference": "NBC 2016 Vol 2, Part 8, Section 1, Clause 4.2"
            },
            {
                "rule_id": "NBC-Part8-Cl3.1",
                "category": "Natural Lighting & Daylight",
                "description": "Minimum 10% effective glazing aperture",
                "status": "PASS" if not any(v["category"] == "Daylight" for v in violations) else "WARN",
                "clause_reference": "NBC 2016 Vol 2, Part 8, Section 1, Clause 3.1"
            },
            {
                "rule_id": "NBC-Part3-Cl10.1",
                "category": "Off-Street Parking",
                "description": "Mandatory vehicular parking space per residential unit",
                "status": "PASS" if not any(v["category"] == "Parking" for v in violations) else "FAIL",
                "clause_reference": "NBC 2016 Vol 1, Part 3, Clause 10.1"
            }
        ]

        total_rules = len(checks_summary)
        failed_count = sum(1 for c in checks_summary if c["status"] == "FAIL")
        warn_count = sum(1 for c in checks_summary if c["status"] == "WARN")
        pass_count = sum(1 for c in checks_summary if c["status"] == "PASS")

        score_pct = round(((pass_count + warn_count * 0.5) / total_rules) * 100, 1)
        overall_status = "COMPLIANT" if failed_count == 0 else "NON_COMPLIANT"

        return {
            "title": "Automated preliminary compliance analysis",
            "jurisdiction": self.jurisdiction,
            "disclaimer": "This analysis is an automated preliminary compliance evaluation generated by algorithmic rule verification and does NOT constitute a licensed legal architectural certification.",
            "overall_status": overall_status,
            "compliance_score_percent": score_pct,
            "summary": {
                "total_rules": total_rules,
                "passed": pass_count,
                "warnings": warn_count,
                "failed": failed_count
            },
            "rule_checks": checks_summary,
            "granular_violations": violations
        }


def check_building_compliance(building_model: Dict[str, Any], jurisdiction: str = "NBC_2016_INDIA") -> Dict[str, Any]:
    """Top-level entrypoint for compliance evaluation"""
    engine = ComplianceReport(building_model, jurisdiction)
    rep = engine.generate_report()
    return {
        "title": rep["title"],
        "jurisdiction": rep["jurisdiction"],
        "disclaimer": rep["disclaimer"],
        "overall_status": rep["overall_status"],
        "score_percent": rep["compliance_score_percent"],
        "total_rules_checked": rep["summary"]["total_rules"],
        "passed_rules": rep["summary"]["passed"],
        "violations": rep["granular_violations"]
    }
